### ISSUE TITLE
Commands in (itemize|enumerate) environments

### ISSUE THREAD

**Issue by kn1cht** [ta2gch/textlint-plugin-latex2e#8]
itemize環境やenumerate環境内で、先頭に`\item`以外のコマンドを使うとパースに失敗します。

```js
  test("itemize", async () => {
    const code = `\\begin{itemize}
        \\tightlist
        \\item 1
        \\item 2
        \\end{itemize}`;
    const ast = LaTeX.Program.tryParse(code); // parse error
  });
```

この状態になりうるのは、リストのスタイルを個別に変更したい場合などです。例えば、[PandocはLaTeXコードの生成時に自動で`\tightlist`を先頭へ挿入します](https://qiita.com/Selene-Misso/items/6c27a4a0947f10af3119)。

`environment/list.ts`で`\item`以外のコマンドも許可すればエラーは出なくなりそうですが、ここで`\item`に限定しているのは何か理由があるのでしょうか？

https://github.com/ta2gch/textlint-plugin-latex2e/blob/ed2c242b4e510147590487644f2ca8b0880771c6/src/latex-to-ast/environment/list.ts#L25-L32

**Comment by ta2gch** [comment]
この問題を解決するにはいくつかの方法があります。

1. 先頭の非アイテム要素を無視する
2. 先頭の非アイテム要素をアイテム要素として、他のアイテム要素と同じように扱う

どちらも本来の意味を損なう点で不適切だと思ったので、保留する意味でこのような仕様にしていました。

**Comment by kn1cht** [comment]
なるほど……
`ASTNodeTypes.List`の中に`ASTNodeTypes.ListItem`以外が入るとまずい、ということですよね？

**Comment by ta2gch** [comment]
はい。もしかしたら、そのような場合でもtextlintは正常に動作するのかもしれませんが、Markdownではそのような状況が起きなかったので、正しく動作するという確証は持てません。もちろん、このまま構文解析に失敗したままではいけないので何かしら決定をする必要はありますね。
